### ISSUE TITLE
Add section about to event guide about using Terminal / Editor / Browser 

### ISSUE THREAD

**Issue by ksaa** [railsgirls/guides.railsgirls.com#16]
Henrietta:
So after tryruby.org (the first three excersises) the coach or person doing the excersises should open the terminal, texteditor and localhost browser. 

Talk about programming workflow, tell people to save (when making changes and seeing it happening in the browser to remember to save it) ... 
Also mention that when running the server, you can't type commands in that terminal. 

Karri did this in Bln and it really helped. 

@gissues:{"order":49.999999999999986,"status":"backlog"}

**Comment by hsbt** [comment]
We have https://guides.railsgirls.com/tools section now.
