### ISSUE TITLE
https://about.google/commitments/?utm_source=about.google&utm_medium=social&utm_campaign=copy-link

### ISSUE THREAD

**Issue by mmu094** [railsgirls/guides.railsgirls.com#521]
Request Id: b3a46e6c-c022-4faa-86cf-c3e971f46300
Correlation Id: 07a91fba-10aa-43c7-938a-445408c69144
Timestamp: 2023-05-15T06:19:22Z
Message: AADSTS500200: User account 'mubashir18@live.com' is a personal Microsoft account. Personal Microsoft accounts are not supported for this application unless explicitly invited to an organization. Try signing out and signing back in with an organizational account.

**Comment by mmu094** [comment]
Check the issue asap

**Comment by tombruijn** [comment]
Hi @mmu094, not sure what your issue is. Can you elaborate?
This seems unrelated to Rails Girls, so I'm closing the issue for now, but feel free to add more information about how we can help.

**Comment by mmu094** [comment]
Hope it is solved 😇
