### ISSUE TITLE
The server certificate has expired: `guides.railsgirls.com`

### ISSUE THREAD

**Issue by urimaro** [railsgirls/guides.railsgirls.com#525]
It seems that the server certificate for Rails Girls Guide( `guides.railsgirls.com` ) has expired.

**Comment by hsbt** [comment]
![Screenshot 2023-06-08 at 13 29 12](https://github.com/railsgirls/guides.railsgirls.com/assets/12301/5728da1f-d0a0-40a6-8a23-abb3045f715f)

GitHub Pages still failed certification renewal.

**Comment by hsbt** [comment]
@ksaa Could you confirm the current DNS configuraiton of `guides.railsgirls.com`?

I confirmed `guides.railsgirls.com` pointed `railsgirls.com` as CNAME now.

```
$ dog guides.railsgirls.com
CNAME guides.railsgirls.com. 5m00s   "railsgirls.com."
```

We should update CNAME with `railsgirls.github.io` for `guides.railsgirls.com`.

**Comment by hsbt** [comment]
@ksaa This issue is still happened. Can you confirm it?

**Comment by ksaa** [comment]
I updated guides.railsgirls.com to point to railsgirls.github.io

**Comment by vesan** [comment]
The certificate is now up to date 👍

**Comment by hsbt** [comment]
@ksaa Thanks! It works now.
