### ISSUE TITLE
Feature : Making a Toggle small button to return to first page 

### ISSUE THREAD

**Issue by VaibhavSharma24** [railsgirls/guides.railsgirls.com#539]
I think by making a small sticky button which on clicking returns to the first page will enhance the web experience as it hard to scroll till up to the main page or i can make the nav bar sticky and by clicking on the logo it returns to main page I am really excited to add this feature if you like it to your website

**Comment by ajay0175** [comment]
hey! I Like to contribute could you assign  me this issue.

**Comment by ajay0175** [comment]
Hey! 
   I would like to work on this feature could you assign me?

**Comment by Sourabhsahu33** [comment]
Can you assigned me this task i will update it according the above instruction.

**Comment by VaibhavSharma24** [comment]
i am currently working on it please look forward for some other changes. Best Wishes

**Comment by VaibhavSharma24** [comment]
please label this as #Hacktoberfest i have requested the pull request
