### ISSUE TITLE
cryptographic protocol(TLS) is not working

### ISSUE THREAD

**Issue by tommyyama2020** [railsgirls/guides.railsgirls.com#551]
It seems that a cryptographic protocol(TLS) is not applicable to Japanese guide. Can anybody take care of this?  Thanks! 
<img width="1003" alt="Screenshot 2023-10-22 at 23 13 37" src="https://github.com/railsgirls/guides.railsgirls.com/assets/38548157/d29f921b-1fe1-4896-bbc3-19a8e917701a">

**Comment by hsbt** [comment]
`railsgirls.jp` is not built by this repository. https://github.com/railsgirls-jp/railsgirls.jp/ is correct.

**Comment by hsbt** [comment]
It's working correctly now.
