### ISSUE TITLE
Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [railsgirls/guides.railsgirls.com#553]
After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

Adding a Scroll to Top Button will improve UX/UI

![image](https://github.com/railsgirls/guides.railsgirls.com/assets/84387676/3f145375-a0fb-4419-9729-4a0a5dde7a82)

**Comment by tombruijn** [comment]
There's already an [issue](https://github.com/railsgirls/guides.railsgirls.com/issues/539) and [PR](https://github.com/railsgirls/guides.railsgirls.com/pull/547) open for this. Closing the duplicate.
